### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by comfortme** [onetune/spotify-web-helper#7] opened 2016-09-18 11:27 UTC
few days ago suddenly it stopped working.
so i think spotify changed some think on their end or updated spotifywebhelper.exe i guess.
i get a "read ECONNRESET" error every time i try to run the code and SpotifyWebHelper.exe crashes shortly after :(

`Error: read ECONNRESET at exports._errnoException (util.js:949:11) at TLSWrap.onread (net.js:563:26)`

**Comment by roncli** [comment] 2016-09-27 23:53
I had the same thing, and noticed they changed the port on me.  I don't know why, but it's now 4371 for me.

Easy enough to deal with:

`var spotify = require("@jonny/spotify-web-helper")({port: 4371});`

With that said, it would be nice if it figured out the port on its own, just in case it changes like this.  A quick scan of Spotify's website shows that it can use any port from 4370 to 4379.

**Comment by comfortme** [comment] 2016-09-28 06:22
yes my port has shifted to 4371 too. 
it would be easy to just try to connect beween 4370-4379 and see if there is a connection or not but as it tries the port 4370 spotifywebhelper crashes. that's interesting

**Comment by JonnyBurger** [comment] 2016-10-01 15:04
Duplicate of #6. 
I've also updated the docs with a notice that this is a TODO. Help appreciated.

**Closed as completed by JonnyBurger** 2016-10-01 15:04 UTC
